name: checks
on:
  - push
  - pull_request
  - workflow_call
jobs:
  test_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/jod', 'latest']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  test_windows:
    if: ${{ !inputs.disable-windows }}
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: ['lts/jod', 'latest']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  lint:
    uses: japa/.github/.github/workflows/lint.yml@main

  typecheck:
    uses: japa/.github/.github/workflows/typecheck.yml@main
